--INSERT VALORES A TABLAS

--VALORES REGION
                INSERT INTO region VALUES(1, 'Tarapacá');
				INSERT INTO region VALUES(2, 'Antofagasta');
				INSERT INTO region VALUES(3, 'Atacama');
				INSERT INTO region VALUES(4, 'Coquimbo');
				INSERT INTO region VALUES(5, 'Valparaíso');
				INSERT INTO region VALUES(6, 'Región del Libertador Gral. Bernardo O''Higgins');
				INSERT INTO region VALUES(7, 'Región del Maule');
				INSERT INTO region VALUES(8, 'Región del Biobío');
				INSERT INTO region VALUES(9, 'Región de la Araucanía');
				INSERT INTO region VALUES(10, 'Región de Los Lagos');
				INSERT INTO region VALUES(11, 'Región Aisén del Gral. Carlos Ibáñez del Campo');
				INSERT INTO region VALUES(12, 'Región de Magallanes y de la Antártica Chilena');
				INSERT INTO region VALUES(13, 'Región Metropolitana de Santiago');
				INSERT INTO region VALUES(14, 'Región de Los Ríos');
				INSERT INTO region VALUES(15, 'Arica y Parinacota');
				INSERT INTO region VALUES(16, 'Región de Ñuble');

--VALORES PROVINCIA
				INSERT INTO provincia VALUES (11, 'Iquique', 1);
				INSERT INTO provincia VALUES (14, 'Tamarugal', 1);
				INSERT INTO provincia VALUES (21, 'Antofagasta', 2);
				INSERT INTO provincia VALUES (22, 'El Loa', 2);
				INSERT INTO provincia VALUES (23, 'Tocopilla', 2);
				INSERT INTO provincia VALUES (31, 'Copiapó', 3);
				INSERT INTO provincia VALUES (32, 'Chañaral', 3);
				INSERT INTO provincia VALUES (33, 'Huasco', 3);
				INSERT INTO provincia VALUES (41, 'Elqui', 4);
				INSERT INTO provincia VALUES (42, 'Choapa', 4);
				INSERT INTO provincia VALUES (43, 'Limarí', 4);
				INSERT INTO provincia VALUES (51, 'Valparaíso', 5);
				INSERT INTO provincia VALUES (52, 'Isla de Pascua', 5);
				INSERT INTO provincia VALUES (53, 'Los Andes', 5);
				INSERT INTO provincia VALUES (54, 'Petorca', 5);
				INSERT INTO provincia VALUES (55, 'Quillota', 5);
				INSERT INTO provincia VALUES (56, 'San Antonio', 5);
				INSERT INTO provincia VALUES (57, 'San Felipe de Aconcagua', 5);
				INSERT INTO provincia VALUES (58, 'Marga Marga', 5);
				INSERT INTO provincia VALUES (61, 'Cachapoal', 6);
				INSERT INTO provincia VALUES (62, 'Cardenal Caro', 6);
				INSERT INTO provincia VALUES (63, 'Colchagua', 6);
				INSERT INTO provincia VALUES (71, 'Talca', 7);
				INSERT INTO provincia VALUES (72, 'Cauquenes', 7);
				INSERT INTO provincia VALUES (73, 'Curicó', 7);
				INSERT INTO provincia VALUES (74, 'Linares', 7);
				INSERT INTO provincia VALUES (81, 'Concepción', 8);
				INSERT INTO provincia VALUES (82, 'Arauco', 8);
				INSERT INTO provincia VALUES (83, 'Biobío', 8);
				INSERT INTO provincia VALUES (91, 'Cautín', 9);
				INSERT INTO provincia VALUES (92, 'Malleco', 9);
				INSERT INTO provincia VALUES (101, 'Llanquihue', 10);
				INSERT INTO provincia VALUES (102, 'Chiloé', 10);
				INSERT INTO provincia VALUES (103, 'Osorno', 10);
				INSERT INTO provincia VALUES (104, 'Palena', 10);
				INSERT INTO provincia VALUES (111, 'Coihaique', 11);
				INSERT INTO provincia VALUES (112, 'Aisén', 11);
				INSERT INTO provincia VALUES (113, 'Capitán Prat', 11);
				INSERT INTO provincia VALUES (114, 'General Carrera', 11);
				INSERT INTO provincia VALUES (121, 'Magallanes', 12);
				INSERT INTO provincia VALUES (122, 'Antártica Chilena', 12);
				INSERT INTO provincia VALUES (123, 'Tierra del Fuego', 12);
				INSERT INTO provincia VALUES (124, 'Última Esperanza', 12);
				INSERT INTO provincia VALUES (131, 'Santiago', 13);
				INSERT INTO provincia VALUES (132, 'Cordillera', 13);
				INSERT INTO provincia VALUES (133, 'Chacabuco', 13);
				INSERT INTO provincia VALUES (134, 'Maipo', 13);
				INSERT INTO provincia VALUES (135, 'Melipilla', 13);
				INSERT INTO provincia VALUES (136, 'Talagante', 13);
				INSERT INTO provincia VALUES (141, 'Valdivia', 14);
				INSERT INTO provincia VALUES (142, 'Ranco', 14);
				INSERT INTO provincia VALUES (151, 'Arica', 15);
				INSERT INTO provincia VALUES (152, 'Parinacota', 15);
				INSERT INTO provincia VALUES (163, 'Diguillín', 16);
				INSERT INTO provincia VALUES (162, 'Itata', 16);
				INSERT INTO provincia VALUES (161, 'Punilla', 16);
                
--VALORES COMUNA
				INSERT INTO comuna VALUES (1101, 'Iquique', 11);
				INSERT INTO comuna VALUES (1107, 'Alto Hospicio', 11);
				INSERT INTO comuna VALUES (1401, 'Pozo Almonte', 14);
				INSERT INTO comuna VALUES (1402, 'Camiña', 14);
				INSERT INTO comuna VALUES (1403, 'Colchane', 14);
				INSERT INTO comuna VALUES (1404, 'Huara', 14);
				INSERT INTO comuna VALUES (1405, 'Pica', 14);
				INSERT INTO comuna VALUES (2101, 'Antofagasta', 21);
				INSERT INTO comuna VALUES (2102, 'Mejillones', 21);
				INSERT INTO comuna VALUES (2103, 'Sierra Gorda', 21);
				INSERT INTO comuna VALUES (2104, 'Taltal', 21);
				INSERT INTO comuna VALUES (2201, 'Calama', 22);
				INSERT INTO comuna VALUES (2202, 'Ollagüe', 22);
				INSERT INTO comuna VALUES (2203, 'San Pedro de Atacama', 22);
				INSERT INTO comuna VALUES (2301, 'Tocopilla', 23);
				INSERT INTO comuna VALUES (2302, 'María Elena', 23);
				INSERT INTO comuna VALUES (3101, 'Copiapó', 31);
				INSERT INTO comuna VALUES (3102, 'Caldera', 31);
				INSERT INTO comuna VALUES (3103, 'Tierra Amarilla', 31);
				INSERT INTO comuna VALUES (3201, 'Chañaral', 32);
				INSERT INTO comuna VALUES (3202, 'Diego de Almagro', 32);
				INSERT INTO comuna VALUES (3301, 'Vallenar', 33);
				INSERT INTO comuna VALUES (3302, 'Alto del Carmen', 33);
				INSERT INTO comuna VALUES (3303, 'Freirina', 33);
				INSERT INTO comuna VALUES (3304, 'Huasco', 33);
				INSERT INTO comuna VALUES (4101, 'La Serena', 41);
				INSERT INTO comuna VALUES (4102, 'Coquimbo', 41);
				INSERT INTO comuna VALUES (4103, 'Andacollo', 41);
				INSERT INTO comuna VALUES (4104, 'La Higuera', 41);
				INSERT INTO comuna VALUES (4105, 'Paihuano', 41);
				INSERT INTO comuna VALUES (4106, 'Vicuña', 41);
				INSERT INTO comuna VALUES (4201, 'Illapel', 42);
				INSERT INTO comuna VALUES (4202, 'Canela', 42);
				INSERT INTO comuna VALUES (4203, 'Los Vilos', 42);
				INSERT INTO comuna VALUES (4204, 'Salamanca', 42);
				INSERT INTO comuna VALUES (4301, 'Ovalle', 43);
				INSERT INTO comuna VALUES (4302, 'Combarbalá', 43);
				INSERT INTO comuna VALUES (4303, 'Monte Patria', 43);
				INSERT INTO comuna VALUES (4304, 'Punitaqui', 43);
				INSERT INTO comuna VALUES (4305, 'Río Hurtado', 43);
				INSERT INTO comuna VALUES (5101, 'Valparaíso', 51);
				INSERT INTO comuna VALUES (5102, 'Casablanca', 51);
				INSERT INTO comuna VALUES (5103, 'Concón', 51);
				INSERT INTO comuna VALUES (5104, 'Juan Fernández', 51);
				INSERT INTO comuna VALUES (5105, 'Puchuncaví', 51);
				INSERT INTO comuna VALUES (5107, 'Quintero', 51);
				INSERT INTO comuna VALUES (5109, 'Viña del Mar', 51);
				INSERT INTO comuna VALUES (5201, 'Isla de Pascua', 52);
				INSERT INTO comuna VALUES (5301, 'Los Andes', 53);
				INSERT INTO comuna VALUES (5302, 'Calle Larga', 53);
				INSERT INTO comuna VALUES (5303, 'Rinconada', 53);
				INSERT INTO comuna VALUES (5304, 'San Esteban', 53);
				INSERT INTO comuna VALUES (5401, 'La Ligua', 54);
				INSERT INTO comuna VALUES (5402, 'Cabildo', 54);
				INSERT INTO comuna VALUES (5403, 'Papudo', 54);
				INSERT INTO comuna VALUES (5404, 'Petorca', 54);
				INSERT INTO comuna VALUES (5405, 'Zapallar', 54);
				INSERT INTO comuna VALUES (5501, 'Quillota', 55);
				INSERT INTO comuna VALUES (5502, 'La Calera', 55);
				INSERT INTO comuna VALUES (5503, 'Hijuelas', 55);
				INSERT INTO comuna VALUES (5504, 'La Cruz', 55);
				INSERT INTO comuna VALUES (5506, 'Nogales', 55);
				INSERT INTO comuna VALUES (5601, 'San Antonio', 56);
				INSERT INTO comuna VALUES (5602, 'Algarrobo', 56);
				INSERT INTO comuna VALUES (5603, 'Cartagena', 56);
				INSERT INTO comuna VALUES (5604, 'El Quisco', 56);
				INSERT INTO comuna VALUES (5605, 'El Tabo', 56);
				INSERT INTO comuna VALUES (5606, 'Santo Domingo', 56);
				INSERT INTO comuna VALUES (5701, 'San Felipe', 57);
				INSERT INTO comuna VALUES (5702, 'Catemu', 57);
				INSERT INTO comuna VALUES (5703, 'Llay Llay', 57);
				INSERT INTO comuna VALUES (5704, 'Panquehue', 57);
				INSERT INTO comuna VALUES (5705, 'Putaendo', 57);
				INSERT INTO comuna VALUES (5706, 'Santa María', 57);
				INSERT INTO comuna VALUES (5801, 'Quilpué', 58);
				INSERT INTO comuna VALUES (5802, 'Limache', 58);
				INSERT INTO comuna VALUES (5803, 'Olmué', 58);
				INSERT INTO comuna VALUES (5804, 'Villa Alemana', 58);
				INSERT INTO comuna VALUES (6101, 'Rancagua', 61);
				INSERT INTO comuna VALUES (6102, 'Codegua', 61);
				INSERT INTO comuna VALUES (6103, 'Coinco', 61);
				INSERT INTO comuna VALUES (6104, 'Coltauco', 61);
				INSERT INTO comuna VALUES (6105, 'Doñihue', 61);
				INSERT INTO comuna VALUES (6106, 'Graneros', 61);
				INSERT INTO comuna VALUES (6107, 'Las Cabras', 61);
				INSERT INTO comuna VALUES (6108, 'Machalí', 61);
				INSERT INTO comuna VALUES (6109, 'Malloa', 61);
				INSERT INTO comuna VALUES (6110, 'Mostazal', 61);
				INSERT INTO comuna VALUES (6111, 'Olivar', 61);
				INSERT INTO comuna VALUES (6112, 'Peumo', 61);
				INSERT INTO comuna VALUES (6113, 'Pichidegua', 61);
				INSERT INTO comuna VALUES (6114, 'Quinta de Tilcoco', 61);
				INSERT INTO comuna VALUES (6115, 'Rengo', 61);
				INSERT INTO comuna VALUES (6116, 'Requínoa', 61);
				INSERT INTO comuna VALUES (6117, 'San Vicente', 61);
				INSERT INTO comuna VALUES (6201, 'Pichilemu', 62);
				INSERT INTO comuna VALUES (6202, 'La Estrella', 62);
				INSERT INTO comuna VALUES (6203, 'Litueche', 62);
				INSERT INTO comuna VALUES (6204, 'Marchihue', 62);
				INSERT INTO comuna VALUES (6205, 'Navidad', 62);
				INSERT INTO comuna VALUES (6206, 'Paredones', 62);
				INSERT INTO comuna VALUES (6301, 'San Fernando', 63);
				INSERT INTO comuna VALUES (6302, 'Chépica', 63);
				INSERT INTO comuna VALUES (6303, 'Chimbarongo', 63);
				INSERT INTO comuna VALUES (6304, 'Lolol', 63);
				INSERT INTO comuna VALUES (6305, 'Nancagua', 63);
				INSERT INTO comuna VALUES (6306, 'Palmilla', 63);
				INSERT INTO comuna VALUES (6307, 'Peralillo', 63);
				INSERT INTO comuna VALUES (6308, 'Placilla', 63);
				INSERT INTO comuna VALUES (6309, 'Pumanque', 63);
				INSERT INTO comuna VALUES (6310, 'Santa Cruz', 63);
				INSERT INTO comuna VALUES (7101, 'Talca', 71);
				INSERT INTO comuna VALUES (7102, 'Constitución', 71);
				INSERT INTO comuna VALUES (7103, 'Curepto', 71);
				INSERT INTO comuna VALUES (7104, 'Empedrado', 71);
				INSERT INTO comuna VALUES (7105, 'Maule', 71);
				INSERT INTO comuna VALUES (7106, 'Pelarco', 71);
				INSERT INTO comuna VALUES (7107, 'Pencahue', 71);
				INSERT INTO comuna VALUES (7108, 'Río Claro', 71);
				INSERT INTO comuna VALUES (7109, 'San Clemente', 71);
				INSERT INTO comuna VALUES (7110, 'San Rafael', 71);
				INSERT INTO comuna VALUES (7201, 'Cauquenes', 72);
				INSERT INTO comuna VALUES (7202, 'Chanco', 72);
				INSERT INTO comuna VALUES (7203, 'Pelluhue', 72);
				INSERT INTO comuna VALUES (7301, 'Curicó', 73);
				INSERT INTO comuna VALUES (7302, 'Hualañé', 73);
				INSERT INTO comuna VALUES (7303, 'Licantén', 73);
				INSERT INTO comuna VALUES (7304, 'Molina', 73);
				INSERT INTO comuna VALUES (7305, 'Rauco', 73);
				INSERT INTO comuna VALUES (7306, 'Romeral', 73);
				INSERT INTO comuna VALUES (7307, 'Sagrada Familia', 73);
				INSERT INTO comuna VALUES (7308, 'Teno', 73);
				INSERT INTO comuna VALUES (7309, 'Vichuquén', 73);
				INSERT INTO comuna VALUES (7401, 'Linares', 74);
				INSERT INTO comuna VALUES (7402, 'Colbún', 74);
				INSERT INTO comuna VALUES (7403, 'Longaví', 74);
				INSERT INTO comuna VALUES (7404, 'Parral', 74);
				INSERT INTO comuna VALUES (7405, 'Retiro', 74);
				INSERT INTO comuna VALUES (7406, 'San Javier', 74);
				INSERT INTO comuna VALUES (7407, 'Villa Alegre', 74);
				INSERT INTO comuna VALUES (7408, 'Yerbas Buenas', 74);
				INSERT INTO comuna VALUES (8101, 'Concepción', 81);
				INSERT INTO comuna VALUES (8102, 'Coronel', 81);
				INSERT INTO comuna VALUES (8103, 'Chiguayante', 81);
				INSERT INTO comuna VALUES (8104, 'Florida', 81);
				INSERT INTO comuna VALUES (8105, 'Hualqui', 81);
				INSERT INTO comuna VALUES (8106, 'Lota', 81);
				INSERT INTO comuna VALUES (8107, 'Penco', 81);
				INSERT INTO comuna VALUES (8108, 'San Pedro de la Paz', 81);
				INSERT INTO comuna VALUES (8109, 'Santa Juana', 81);
				INSERT INTO comuna VALUES (8110, 'Talcahuano', 81);
				INSERT INTO comuna VALUES (8111, 'Tomé', 81);
				INSERT INTO comuna VALUES (8112, 'Hualpén', 81);
				INSERT INTO comuna VALUES (8201, 'Lebu', 82);
				INSERT INTO comuna VALUES (8202, 'Arauco', 82);
				INSERT INTO comuna VALUES (8203, 'Cañete', 82);
				INSERT INTO comuna VALUES (8204, 'Contulmo', 82);
				INSERT INTO comuna VALUES (8205, 'Curanilahue', 82);
				INSERT INTO comuna VALUES (8206, 'Los Álamos', 82);
				INSERT INTO comuna VALUES (8207, 'Tirúa', 82);
				INSERT INTO comuna VALUES (8301, 'Los Ángeles', 83);
				INSERT INTO comuna VALUES (8302, 'Antuco', 83);
				INSERT INTO comuna VALUES (8303, 'Cabrero', 83);
				INSERT INTO comuna VALUES (8304, 'Laja', 83);
				INSERT INTO comuna VALUES (8305, 'Mulchén', 83);
				INSERT INTO comuna VALUES (8306, 'Nacimiento', 83);
				INSERT INTO comuna VALUES (8307, 'Negrete', 83);
				INSERT INTO comuna VALUES (8308, 'Quilaco', 83);
				INSERT INTO comuna VALUES (8309, 'Quilleco', 83);
				INSERT INTO comuna VALUES (8310, 'San Rosendo', 83);
				INSERT INTO comuna VALUES (8311, 'Santa Bárbara', 83);
				INSERT INTO comuna VALUES (8312, 'Tucapel', 83);
				INSERT INTO comuna VALUES (8313, 'Yumbel', 83);
				INSERT INTO comuna VALUES (8314, 'Alto Biobío', 83);
				INSERT INTO comuna VALUES (9101, 'Temuco', 91);
				INSERT INTO comuna VALUES (9102, 'Carahue', 91);
				INSERT INTO comuna VALUES (9103, 'Cunco', 91);
				INSERT INTO comuna VALUES (9104, 'Curarrehue', 91);
				INSERT INTO comuna VALUES (9105, 'Freire', 91);
				INSERT INTO comuna VALUES (9106, 'Galvarino', 91);
				INSERT INTO comuna VALUES (9107, 'Gorbea', 91);
				INSERT INTO comuna VALUES (9108, 'Lautaro', 91);
				INSERT INTO comuna VALUES (9109, 'Loncoche', 91);
				INSERT INTO comuna VALUES (9110, 'Melipeuco', 91);
				INSERT INTO comuna VALUES (9111, 'Nueva Imperial', 91);
				INSERT INTO comuna VALUES (9112, 'Padre las Casas', 91);
				INSERT INTO comuna VALUES (9113, 'Perquenco', 91);
				INSERT INTO comuna VALUES (9114, 'Pitrufquén', 91);
				INSERT INTO comuna VALUES (9115, 'Pucón', 91);
				INSERT INTO comuna VALUES (9116, 'Saavedra', 91);
				INSERT INTO comuna VALUES (9117, 'Teodoro Schmidt', 91);
				INSERT INTO comuna VALUES (9118, 'Toltén', 91);
				INSERT INTO comuna VALUES (9119, 'Vilcún', 91);
				INSERT INTO comuna VALUES (9120, 'Villarrica', 91);
				INSERT INTO comuna VALUES (9121, 'Cholchol', 91);
				INSERT INTO comuna VALUES (9201, 'Angol', 92);
				INSERT INTO comuna VALUES (9202, 'Collipulli', 92);
				INSERT INTO comuna VALUES (9203, 'Curacautín', 92);
				INSERT INTO comuna VALUES (9204, 'Ercilla', 92);
				INSERT INTO comuna VALUES (9205, 'Lonquimay', 92);
				INSERT INTO comuna VALUES (9206, 'Los Sauces', 92);
				INSERT INTO comuna VALUES (9207, 'Lumaco', 92);
				INSERT INTO comuna VALUES (9208, 'Purén', 92);
				INSERT INTO comuna VALUES (9209, 'Renaico', 92);
				INSERT INTO comuna VALUES (9210, 'Traiguén', 92);
				INSERT INTO comuna VALUES (9211, 'Victoria', 92);
				INSERT INTO comuna VALUES (10101, 'Puerto Montt', 101);
				INSERT INTO comuna VALUES (10102, 'Calbuco', 101);
				INSERT INTO comuna VALUES (10103, 'Cochamó', 101);
				INSERT INTO comuna VALUES (10104, 'Fresia', 101);
				INSERT INTO comuna VALUES (10105, 'Frutillar', 101);
				INSERT INTO comuna VALUES (10106, 'Los Muermos', 101);
				INSERT INTO comuna VALUES (10107, 'Llanquihue', 101);
				INSERT INTO comuna VALUES (10108, 'Maullín', 101);
				INSERT INTO comuna VALUES (10109, 'Puerto Varas', 101);
				INSERT INTO comuna VALUES (10201, 'Castro', 102);
				INSERT INTO comuna VALUES (10202, 'Ancud', 102);
				INSERT INTO comuna VALUES (10203, 'Chonchi', 102);
				INSERT INTO comuna VALUES (10204, 'Curaco de Vélez', 102);
				INSERT INTO comuna VALUES (10205, 'Dalcahue', 102);
				INSERT INTO comuna VALUES (10206, 'Puqueldón', 102);
				INSERT INTO comuna VALUES (10207, 'Queilén', 102);
				INSERT INTO comuna VALUES (10208, 'Quellón', 102);
				INSERT INTO comuna VALUES (10209, 'Quemchi', 102);
				INSERT INTO comuna VALUES (10210, 'Quinchao', 102);
				INSERT INTO comuna VALUES (10301, 'Osorno', 103);
				INSERT INTO comuna VALUES (10302, 'Puerto Octay', 103);
				INSERT INTO comuna VALUES (10303, 'Purranque', 103);
				INSERT INTO comuna VALUES (10304, 'Puyehue', 103);
				INSERT INTO comuna VALUES (10305, 'Río Negro', 103);
				INSERT INTO comuna VALUES (10306, 'San Juan de la Costa', 103);
				INSERT INTO comuna VALUES (10307, 'San Pablo', 103);
				INSERT INTO comuna VALUES (10401, 'Chaitén', 104);
				INSERT INTO comuna VALUES (10402, 'Futaleufú', 104);
				INSERT INTO comuna VALUES (10403, 'Hualaihué', 104);
				INSERT INTO comuna VALUES (10404, 'Palena', 104);
				INSERT INTO comuna VALUES (11101, 'Coyhaique', 111);
				INSERT INTO comuna VALUES (11102, 'Lago Verde', 111);
				INSERT INTO comuna VALUES (11201, 'Aysén', 112);
				INSERT INTO comuna VALUES (11202, 'Cisnes', 112);
				INSERT INTO comuna VALUES (11203, 'Guaitecas', 112);
				INSERT INTO comuna VALUES (11301, 'Cochrane', 113);
				INSERT INTO comuna VALUES (11302, 'O''Higgins', 113);
				INSERT INTO comuna VALUES (11303, 'Tortel', 113);
				INSERT INTO comuna VALUES (11401, 'Chile Chico', 114);
				INSERT INTO comuna VALUES (11402, 'Río Ibáñez', 114);
				INSERT INTO comuna VALUES (12101, 'Punta Arenas', 121);
				INSERT INTO comuna VALUES (12102, 'Laguna Blanca', 121);
				INSERT INTO comuna VALUES (12103, 'Río Verde', 121);
				INSERT INTO comuna VALUES (12104, 'San Gregorio', 121);
				INSERT INTO comuna VALUES (12201, 'Cabo de Hornos', 122);
				INSERT INTO comuna VALUES (12202, 'Antártica', 122);
				INSERT INTO comuna VALUES (12301, 'Porvenir', 123);
				INSERT INTO comuna VALUES (12302, 'Primavera', 123);
				INSERT INTO comuna VALUES (12303, 'Timaukel', 123);
				INSERT INTO comuna VALUES (12401, 'Natales', 124);
				INSERT INTO comuna VALUES (12402, 'Torres del Paine', 124);
				INSERT INTO comuna VALUES (13101, 'Santiago', 131);
				INSERT INTO comuna VALUES (13102, 'Cerrillos', 131);
				INSERT INTO comuna VALUES (13103, 'Cerro Navia', 131);
				INSERT INTO comuna VALUES (13104, 'Conchalí', 131);
				INSERT INTO comuna VALUES (13105, 'El Bosque', 131);
				INSERT INTO comuna VALUES (13106, 'Estación Central', 131);
				INSERT INTO comuna VALUES (13107, 'Huechuraba', 131);
				INSERT INTO comuna VALUES (13108, 'Independencia', 131);
				INSERT INTO comuna VALUES (13109, 'La Cisterna', 131);
				INSERT INTO comuna VALUES (13110, 'La Florida', 131);
				INSERT INTO comuna VALUES (13111, 'La Granja', 131);
				INSERT INTO comuna VALUES (13112, 'La Pintana', 131);
				INSERT INTO comuna VALUES (13113, 'La Reina', 131);
				INSERT INTO comuna VALUES (13114, 'Las Condes', 131);
				INSERT INTO comuna VALUES (13115, 'Lo Barnechea', 131);
				INSERT INTO comuna VALUES (13116, 'Lo Espejo', 131);
				INSERT INTO comuna VALUES (13117, 'Lo Prado', 131);
				INSERT INTO comuna VALUES (13118, 'Macul', 131);
				INSERT INTO comuna VALUES (13119, 'Maipú', 131);
				INSERT INTO comuna VALUES (13120, 'Ñuñoa', 131);
				INSERT INTO comuna VALUES (13121, 'Pedro Aguirre Cerda', 131);
				INSERT INTO comuna VALUES (13122, 'Peñalolén', 131);
				INSERT INTO comuna VALUES (13123, 'Providencia', 131);
				INSERT INTO comuna VALUES (13124, 'Pudahuel', 131);
				INSERT INTO comuna VALUES (13125, 'Quilicura', 131);
				INSERT INTO comuna VALUES (13126, 'Quinta Normal', 131);
				INSERT INTO comuna VALUES (13127, 'Recoleta', 131);
				INSERT INTO comuna VALUES (13128, 'Renca', 131);
				INSERT INTO comuna VALUES (13129, 'San Joaquín', 131);
				INSERT INTO comuna VALUES (13130, 'San Miguel', 131);
				INSERT INTO comuna VALUES (13131, 'San Ramón', 131);
				INSERT INTO comuna VALUES (13132, 'Vitacura', 131);
				INSERT INTO comuna VALUES (13201, 'Puente Alto', 132);
				INSERT INTO comuna VALUES (13202, 'Pirque', 132);
				INSERT INTO comuna VALUES (13203, 'San José de Maipo', 132);
				INSERT INTO comuna VALUES (13301, 'Colina', 133);
				INSERT INTO comuna VALUES (13302, 'Lampa', 133);
				INSERT INTO comuna VALUES (13303, 'Tiltil', 133);
				INSERT INTO comuna VALUES (13401, 'San Bernardo', 134);
				INSERT INTO comuna VALUES (13402, 'Buin', 134);
				INSERT INTO comuna VALUES (13403, 'Calera de Tango', 134);
				INSERT INTO comuna VALUES (13404, 'Paine', 134);
				INSERT INTO comuna VALUES (13501, 'Melipilla', 135);
				INSERT INTO comuna VALUES (13502, 'Alhué', 135);
				INSERT INTO comuna VALUES (13503, 'Curacaví', 135);
				INSERT INTO comuna VALUES (13504, 'María PINSERT INTO', 135);
				INSERT INTO comuna VALUES (13505, 'San Pedro', 135);
				INSERT INTO comuna VALUES (13601, 'Talagante', 136);
				INSERT INTO comuna VALUES (13602, 'El Monte', 136);
				INSERT INTO comuna VALUES (13603, 'Isla de Maipo', 136);
				INSERT INTO comuna VALUES (13604, 'Padre Hurtado', 136);
				INSERT INTO comuna VALUES (13605, 'Peñaflor', 136);
				INSERT INTO comuna VALUES (14101, 'Valdivia', 141);
				INSERT INTO comuna VALUES (14102, 'Corral', 141);
				INSERT INTO comuna VALUES (14103, 'Lanco', 141);
				INSERT INTO comuna VALUES (14104, 'Los Lagos', 141);
				INSERT INTO comuna VALUES (14105, 'Máfil', 141);
				INSERT INTO comuna VALUES (14106, 'Mariquina', 141);
				INSERT INTO comuna VALUES (14107, 'Paillaco', 141);
				INSERT INTO comuna VALUES (14108, 'Panguipulli', 141);
				INSERT INTO comuna VALUES (14201, 'La Unión', 142);
				INSERT INTO comuna VALUES (14202, 'Futrono', 142);
				INSERT INTO comuna VALUES (14203, 'Lago Ranco', 142);
				INSERT INTO comuna VALUES (14204, 'Río Bueno', 142);
				INSERT INTO comuna VALUES (15101, 'Arica', 151);
				INSERT INTO comuna VALUES (15102, 'Camarones', 151);
				INSERT INTO comuna VALUES (15201, 'Putre', 152);
				INSERT INTO comuna VALUES (15202, 'General Lagos', 152);
				INSERT INTO comuna VALUES (8401, 'Chillán', 163);
				INSERT INTO comuna VALUES (8402, 'Bulnes', 163);
				INSERT INTO comuna VALUES (8406, 'Chillán Viejo', 163);
				INSERT INTO comuna VALUES (8407, 'El Carmen', 163);
				INSERT INTO comuna VALUES (8410, 'Pemuco', 163);
				INSERT INTO comuna VALUES (8411, 'PINSERT INTO', 163);
				INSERT INTO comuna VALUES (8413, 'Quillón', 163);
				INSERT INTO comuna VALUES (8418, 'San Ignacio', 163);
				INSERT INTO comuna VALUES (8421, 'Yungay', 163);
				INSERT INTO comuna VALUES (8403, 'Cobquecura', 162);
				INSERT INTO comuna VALUES (8404, 'Coelemu', 162);
				INSERT INTO comuna VALUES (8408, 'Ninhue', 162);
				INSERT INTO comuna VALUES (8412, 'Portezuelo', 162);
				INSERT INTO comuna VALUES (8414, 'Quirihue', 162);
				INSERT INTO comuna VALUES (8415, 'Ránquil', 162);
				INSERT INTO comuna VALUES (8420, 'Treguaco', 162);
				INSERT INTO comuna VALUES (8405, 'Coihueco', 161);
				INSERT INTO comuna VALUES (8409, 'Ñiquén', 161);
				INSERT INTO comuna VALUES (8416, 'San Carlos', 161);
				INSERT INTO comuna VALUES (8417, 'San Fabián', 161);
				INSERT INTO comuna VALUES (8419, 'San Nicolás', 161);
                
--VAORES NACIONALIDAD
                INSERT INTO NAC VALUES (1 , 'AFGHANISTAN');
                INSERT INTO NAC VALUES (2 , 'ALAND ISLANDS');
                INSERT INTO NAC VALUES (3 , 'ALBANIA');
                INSERT INTO NAC VALUES (4 , 'ALEMANIA');
                INSERT INTO NAC VALUES (5 , 'ALGERIA');
                INSERT INTO NAC VALUES (6 , 'AMERICAN SAMOA');
                INSERT INTO NAC VALUES (7 , 'ANDORRA');
                INSERT INTO NAC VALUES (8 , 'ANGOLA');
                INSERT INTO NAC VALUES (9 , 'ANGUILLA');
                INSERT INTO NAC VALUES (10 , 'ANTARCTICA');
                INSERT INTO NAC VALUES (11 , 'ANTIGUA Y BARBUDA');
                INSERT INTO NAC VALUES (12 , 'ARABIA SAUDITA');
                INSERT INTO NAC VALUES (13 , 'ARGENTINA');
                INSERT INTO NAC VALUES (14 , 'ARMENIA');
                INSERT INTO NAC VALUES (15 , 'ARUBA');
                INSERT INTO NAC VALUES (16 , 'ASIA / REGION PACIFICO');
                INSERT INTO NAC VALUES (17 , 'AUSTRALIA');
                INSERT INTO NAC VALUES (18 , 'AUSTRIA');
                INSERT INTO NAC VALUES (19 , 'AZERBAIJAN');
                INSERT INTO NAC VALUES (20 , 'BAHAMAS');
                INSERT INTO NAC VALUES (21 , 'BAHRAIN');
                INSERT INTO NAC VALUES (22 , 'BANGLADESH');
                INSERT INTO NAC VALUES (23 , 'BARBADOS');
                INSERT INTO NAC VALUES (24 , 'BELARUS');
                INSERT INTO NAC VALUES (25 , 'BELGICA');
                INSERT INTO NAC VALUES (26 , 'BELICE');
                INSERT INTO NAC VALUES (27 , 'BENIN');
                INSERT INTO NAC VALUES (28 , 'BERMUDA');
                INSERT INTO NAC VALUES (29 , 'BHUTAN');
                INSERT INTO NAC VALUES (30 , 'BOLIVIA');
                INSERT INTO NAC VALUES (31 , 'BONAIR');
                INSERT INTO NAC VALUES (32 , 'BOSNIA AND HERZEGOVINA');
                INSERT INTO NAC VALUES (33 , 'BOTSWANA');
                INSERT INTO NAC VALUES (34 , 'BRASIL');
                INSERT INTO NAC VALUES (35 , 'BRITISH INDIAN OCEAN TERRITORY');
                INSERT INTO NAC VALUES (36 , 'BRUNEI DARUSSALAM');
                INSERT INTO NAC VALUES (37 , 'BULGARIA');
                INSERT INTO NAC VALUES (38 , 'BURKINA FASO');
                INSERT INTO NAC VALUES (39 , 'BURUNDI');
                INSERT INTO NAC VALUES (40 , 'CABO VERDE');
                INSERT INTO NAC VALUES (41 , 'CAMBOYA');
                INSERT INTO NAC VALUES (42 , 'CAMERUN');
                INSERT INTO NAC VALUES (43 , 'CANADA');
                INSERT INTO NAC VALUES (44 , 'CHAD');
                INSERT INTO NAC VALUES (45 , 'CHILE');
                INSERT INTO NAC VALUES (46 , 'CHINA');
                INSERT INTO NAC VALUES (47 , 'CHIPRE');
                INSERT INTO NAC VALUES (48 , 'COCOS (KEELING) ISLANDS');
                INSERT INTO NAC VALUES (49 , 'COLOMBIA');
                INSERT INTO NAC VALUES (50 , 'COMOROS');
                INSERT INTO NAC VALUES (51 , 'CONG');
                INSERT INTO NAC VALUES (52 , 'CONGO');
                INSERT INTO NAC VALUES (53 , 'COOK ISLANDS');
                INSERT INTO NAC VALUES (54 , 'COSTA RICA');
                INSERT INTO NAC VALUES (55 , 'COTE D IVOIRE');
                INSERT INTO NAC VALUES (56 , 'CROACIA');
                INSERT INTO NAC VALUES (57 , 'CUBA');
                INSERT INTO NAC VALUES (58 , 'CURACAO');
                INSERT INTO NAC VALUES (59 , 'DINAMARCA');
                INSERT INTO NAC VALUES (60 , 'DJIBOUTI');
                INSERT INTO NAC VALUES (61 , 'DOMINICA');
                INSERT INTO NAC VALUES (62 , 'ECUADOR');
                INSERT INTO NAC VALUES (63 , 'EGIPTO');
                INSERT INTO NAC VALUES (64 , 'EL SALVADOR');
                INSERT INTO NAC VALUES (65 , 'EMIRATOS ARABES UNIDOS');
                INSERT INTO NAC VALUES (66 , 'ERITREA');
                INSERT INTO NAC VALUES (67 , 'ESLOVAQUIA');
                INSERT INTO NAC VALUES (68 , 'ESLOVENIA');
                INSERT INTO NAC VALUES (69 , 'ESPAÑA');
                INSERT INTO NAC VALUES (70 , 'ESTADOS UNIDOS');
                INSERT INTO NAC VALUES (71 , 'ESTONIA');
                INSERT INTO NAC VALUES (72 , 'ETIOPIA');
                INSERT INTO NAC VALUES (73 , 'FAROE ISLANDS');
                INSERT INTO NAC VALUES (74 , 'FIJI');
                INSERT INTO NAC VALUES (75 , 'FILIPINAS');
                INSERT INTO NAC VALUES (76 , 'FINLANDIA');
                INSERT INTO NAC VALUES (77 , 'FRANCIA');
                INSERT INTO NAC VALUES (78 , 'FRENCH POLYNESIA');
                INSERT INTO NAC VALUES (79 , 'GABON');
                INSERT INTO NAC VALUES (80 , 'GAMBIA');
                INSERT INTO NAC VALUES (81 , 'GANA');
                INSERT INTO NAC VALUES (82 , 'GEORGIA');
                INSERT INTO NAC VALUES (83 , 'GIBRALTAR');
                INSERT INTO NAC VALUES (84 , 'GRANADA');
                INSERT INTO NAC VALUES (85 , 'GRECIA');
                INSERT INTO NAC VALUES (86 , 'GROENLANDIA');
                INSERT INTO NAC VALUES (87 , 'GUADELOUPE');
                INSERT INTO NAC VALUES (88 , 'GUAM');
                INSERT INTO NAC VALUES (89 , 'GUATEMALA');
                INSERT INTO NAC VALUES (90 , 'GUERNSEY');
                INSERT INTO NAC VALUES (91 , 'GUINEA');
                INSERT INTO NAC VALUES (92 , 'GUINEA ECUATORIAL');
                INSERT INTO NAC VALUES (93 , 'GUINEA-BISSAU');
                INSERT INTO NAC VALUES (94 , 'GUYANA');
                INSERT INTO NAC VALUES (95 , 'GUYANA FRANCESA');
                INSERT INTO NAC VALUES (96 , 'HAITI');
                INSERT INTO NAC VALUES (97 , 'HOLANDA, PAISES BAJOS');
                INSERT INTO NAC VALUES (98 , 'HOLY SEE (VATICAN CITY STATE)');
                INSERT INTO NAC VALUES (99 , 'HONDURAS');
                INSERT INTO NAC VALUES (100 , 'HUNGRIA');
                INSERT INTO NAC VALUES (101 , 'INDIA');
                INSERT INTO NAC VALUES (102 , 'INDONESIA');
                INSERT INTO NAC VALUES (103 , 'IRA');
                INSERT INTO NAC VALUES (104 , 'IRAQ');
                INSERT INTO NAC VALUES (105 , 'IRLANDA');
                INSERT INTO NAC VALUES (106 , 'ISLANDIA');
                INSERT INTO NAC VALUES (107 , 'ISLAS (MALVINAS)');
                INSERT INTO NAC VALUES (108 , 'ISLAS CAIMAN');
                INSERT INTO NAC VALUES (109 , 'ISLAS DE PASCUA');
                INSERT INTO NAC VALUES (110 , 'ISLAS SALOMON');
                INSERT INTO NAC VALUES (111 , 'ISLE OF MAN');
                INSERT INTO NAC VALUES (112 , 'ISRAEL');
                INSERT INTO NAC VALUES (113 , 'ITALIA');
                INSERT INTO NAC VALUES (114 , 'JAMAICA');
                INSERT INTO NAC VALUES (115 , 'JAPAN');
                INSERT INTO NAC VALUES (116 , 'JERSEY');
                INSERT INTO NAC VALUES (117 , 'JORDAN');
                INSERT INTO NAC VALUES (118 , 'KAZAKHSTAN');
                INSERT INTO NAC VALUES (119 , 'KENYA');
                INSERT INTO NAC VALUES (120 , 'KIRIBATI');
                INSERT INTO NAC VALUES (121 , 'KORE');
                INSERT INTO NAC VALUES (122 , 'KUWAIT');
                INSERT INTO NAC VALUES (123 , 'KYRGYZSTAN');
                INSERT INTO NAC VALUES (124 , 'LAO PEOPLES DEMOCRATIC REPUBLIC');
                INSERT INTO NAC VALUES (125 , 'LATVIA');
                INSERT INTO NAC VALUES (126 , 'LEBANON');
                INSERT INTO NAC VALUES (127 , 'LESOTHO');
                INSERT INTO NAC VALUES (128 , 'LIBERIA');
                INSERT INTO NAC VALUES (129 , 'LIBYA');
                INSERT INTO NAC VALUES (130 , 'LIECHTENSTEIN');
                INSERT INTO NAC VALUES (131 , 'LITHUANIA');
                INSERT INTO NAC VALUES (132 , 'LUXEMBOURG');
                INSERT INTO NAC VALUES (133 , 'MACAU');
                INSERT INTO NAC VALUES (134 , 'MACEDONIA');
                INSERT INTO NAC VALUES (135 , 'MADAGASCAR');
                INSERT INTO NAC VALUES (136 , 'MALASIA');
                INSERT INTO NAC VALUES (137 , 'MALAWI');
                INSERT INTO NAC VALUES (138 , 'MALDIVES');
                INSERT INTO NAC VALUES (139 , 'MALI');
                INSERT INTO NAC VALUES (140 , 'MALTA');
                INSERT INTO NAC VALUES (141 , 'MARRUECOS');
                INSERT INTO NAC VALUES (142 , 'MARSHALL ISLANDS');
                INSERT INTO NAC VALUES (143 , 'MARTINIQUE');
                INSERT INTO NAC VALUES (144 , 'MAURITANIA');
                INSERT INTO NAC VALUES (145 , 'MAURITIUS');
                INSERT INTO NAC VALUES (146 , 'MAYOTTE');
                INSERT INTO NAC VALUES (147 , 'MEXICO');
                INSERT INTO NAC VALUES (148 , 'MICRONESI');
                INSERT INTO NAC VALUES (149 , 'MOLDOV');
                INSERT INTO NAC VALUES (150 , 'MONACO');
                INSERT INTO NAC VALUES (151 , 'MONGOLIA');
                INSERT INTO NAC VALUES (152 , 'MONTENEGRO');
                INSERT INTO NAC VALUES (153 , 'MONTSERRAT');
                INSERT INTO NAC VALUES (154 , 'MOZAMBIQUE');
                INSERT INTO NAC VALUES (155 , 'MYANMAR');
                INSERT INTO NAC VALUES (156 , 'NAMIBIA');
                INSERT INTO NAC VALUES (157 , 'NAURU');
                INSERT INTO NAC VALUES (158 , 'NEPAL');
                INSERT INTO NAC VALUES (159 , 'NICARAGUA');
                INSERT INTO NAC VALUES (160 , 'NIGER');
                INSERT INTO NAC VALUES (161 , 'NIGERIA');
                INSERT INTO NAC VALUES (162 , 'NIUE');
                INSERT INTO NAC VALUES (163 , 'NORFOLK ISLAND');
                INSERT INTO NAC VALUES (164 , 'NORTHERN MARIANA ISLANDS');
                INSERT INTO NAC VALUES (165 , 'NORUEGA');
                INSERT INTO NAC VALUES (166 , 'NUEVA CALEDONIA');
                INSERT INTO NAC VALUES (167 , 'NUEVA ZELANDIA');
                INSERT INTO NAC VALUES (168 , 'OMAN');
                INSERT INTO NAC VALUES (169 , 'PAKISTAN');
                INSERT INTO NAC VALUES (170 , 'PALAU');
                INSERT INTO NAC VALUES (171 , 'PALESTINA');
                INSERT INTO NAC VALUES (172 , 'PANAMA');
                INSERT INTO NAC VALUES (173 , 'PAPUA NEW GUINEA');
                INSERT INTO NAC VALUES (174 , 'PARAGUAY');
                INSERT INTO NAC VALUES (175 , 'PERU');
                INSERT INTO NAC VALUES (176 , 'PITCAIRN ISLANDS');
                INSERT INTO NAC VALUES (177 , 'POLONIA');
                INSERT INTO NAC VALUES (178 , 'PORTUGAL');
                INSERT INTO NAC VALUES (179 , 'PUERTO RICO');
                INSERT INTO NAC VALUES (180 , 'QATAR');
                INSERT INTO NAC VALUES (181 , 'REINO UNIDO');
                INSERT INTO NAC VALUES (182 , 'REPUBLICA CENTRAL DE AFRICA');
                INSERT INTO NAC VALUES (183 , 'REPUBLICA CHECA');
                INSERT INTO NAC VALUES (184 , 'REPUBLICA DOMINICANA');
                INSERT INTO NAC VALUES (185 , 'REUNION');
                INSERT INTO NAC VALUES (186 , 'ROMANIA');
                INSERT INTO NAC VALUES (187 , 'RUANDA');
                INSERT INTO NAC VALUES (188 , 'RUSIA');
                INSERT INTO NAC VALUES (189 , 'SAINT BARTHELEMY');
                INSERT INTO NAC VALUES (190 , 'SAINT HELENA');
                INSERT INTO NAC VALUES (191 , 'SAINT KITTS AND NEVIS');
                INSERT INTO NAC VALUES (192 , 'SAINT PIERRE AND MIQUELON');
                INSERT INTO NAC VALUES (193 , 'SAINT VINCENT AND THE GRENADINES');
                INSERT INTO NAC VALUES (194 , 'SAMOA');
                INSERT INTO NAC VALUES (195 , 'SAN MARINO');
                INSERT INTO NAC VALUES (196 , 'SAN MARTIN');
                INSERT INTO NAC VALUES (197 , 'SANTA LUCIA');
                INSERT INTO NAC VALUES (198 , 'SAO TOME AND PRINCIPE');
                INSERT INTO NAC VALUES (199 , 'SENEGAL');
                INSERT INTO NAC VALUES (200 , 'SERBIA');
                INSERT INTO NAC VALUES (201 , 'SEYCHELLES');
                INSERT INTO NAC VALUES (202 , 'SIERRA LEONE');
                INSERT INTO NAC VALUES (203 , 'SINGAPUR');
                INSERT INTO NAC VALUES (204 , 'SINT MAARTEN (DUTCH PART)');
                INSERT INTO NAC VALUES (205 , 'SIRIA REPUBLICA ARABE');
                INSERT INTO NAC VALUES (206 , 'SOMALIA');
                INSERT INTO NAC VALUES (207 , 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
                INSERT INTO NAC VALUES (208 , 'SRI LANKA');
                INSERT INTO NAC VALUES (209 , 'SUDAFRICA');
                INSERT INTO NAC VALUES (210 , 'SUDAN');
                INSERT INTO NAC VALUES (211 , 'SUDAN DEL SUR');
                INSERT INTO NAC VALUES (212 , 'SUECIA');
                INSERT INTO NAC VALUES (213 , 'SUIZA');
                INSERT INTO NAC VALUES (214 , 'SURINAM');
                INSERT INTO NAC VALUES (215 , 'SVALBARD AND JAN MAYEN');
                INSERT INTO NAC VALUES (216 , 'SWAZILAND');
                INSERT INTO NAC VALUES (217 , 'TAILANDIA');
                INSERT INTO NAC VALUES (218 , 'TAIWAN');
                INSERT INTO NAC VALUES (219 , 'TAJIKISTAN');
                INSERT INTO NAC VALUES (220 , 'TANZANIA');
                INSERT INTO NAC VALUES (221 , 'TIMOR-LESTE');
                INSERT INTO NAC VALUES (222 , 'TOGO');
                INSERT INTO NAC VALUES (223 , 'TOKELAU');
                INSERT INTO NAC VALUES (224 , 'TONGA');
                INSERT INTO NAC VALUES (225 , 'TRINIDAD Y TOBAGO');
                INSERT INTO NAC VALUES (226 , 'TUNISIA');
                INSERT INTO NAC VALUES (227 , 'TURKMENISTAN');
                INSERT INTO NAC VALUES (228 , 'TURKS AND CAICOS ISLANDS');
                INSERT INTO NAC VALUES (229 , 'TURQUIA');
                INSERT INTO NAC VALUES (230 , 'TUVALU');
                INSERT INTO NAC VALUES (231 , 'UCRANIA');
                INSERT INTO NAC VALUES (232 , 'UGANDA');
                INSERT INTO NAC VALUES (233 , 'UNITED STATES MINOR OUTLYING ISLANDS');
                INSERT INTO NAC VALUES (234 , 'URUGUAY');
                INSERT INTO NAC VALUES (235 , 'UZBEKISTAN');
                INSERT INTO NAC VALUES (236 , 'VANUATU');
                INSERT INTO NAC VALUES (237 , 'VENEZUELA');
                INSERT INTO NAC VALUES (238 , 'VIETNAM');
                INSERT INTO NAC VALUES (239 , 'VIRGIN ISLAND');
                INSERT INTO NAC VALUES (240 , 'WALLIS AND FUTUNA');
                INSERT INTO NAC VALUES (241 , 'WESTERN SAHARA');
                INSERT INTO NAC VALUES (242 , 'YEMEN');
                INSERT INTO NAC VALUES (243 , 'ZAMBIA');
                INSERT INTO NAC VALUES (244 , 'ZIMBABWE');
                
--VALORES ESTADO CIVIL
                INSERT INTO EST_CIVIL VALUES (1, 'Casado');
                INSERT INTO EST_CIVIL VALUES (2, 'Conviviente civil');
                INSERT INTO EST_CIVIL VALUES (3, 'Soltero');
                INSERT INTO EST_CIVIL VALUES (4, 'Divorsiado');
                INSERT INTO EST_CIVIL VALUES (5, 'Viudo');
        
--VALORES BANCO
                INSERT INTO BANCO VALUES (1,'Banco de Chile');
                INSERT INTO BANCO VALUES (2,'Banco Internacional');
                INSERT INTO BANCO VALUES (3,'Scotiabank Chile');
                INSERT INTO BANCO VALUES (4,'BCI');
                INSERT INTO BANCO VALUES (5,'Corpbanca');
                INSERT INTO BANCO VALUES (6,'Banco Bice');
                INSERT INTO BANCO VALUES (7,'HSBC Bank (Chile)');
                INSERT INTO BANCO VALUES (8,'Banco Santander');
                INSERT INTO BANCO VALUES (9,'Banco Itaú Chile');
                INSERT INTO BANCO VALUES (10,'Banco Security');
                INSERT INTO BANCO VALUES (11,'Banco Falabella');
                INSERT INTO BANCO VALUES (12,'Deutsche Bank');
                INSERT INTO BANCO VALUES (13,'Banco RIpley');
                INSERT INTO BANCO VALUES (14,'Rabobank Chile');
                INSERT INTO BANCO VALUES (15,'Banco Consorcio');
                INSERT INTO BANCO VALUES (16,'Banco Penta');
                INSERT INTO BANCO VALUES (17,'Banco Paris');
                INSERT INTO BANCO VALUES (18,'BBVA');
                INSERT INTO BANCO VALUES (19,'BTG Pactual Chile');